import type { Game, HS } from '@';

export const SETS: Record<string, string> = {
  CORE: 'Core',
  EVENT: 'Event',
  NAXX: 'Curse of Naxxramas',
  GVG: 'Goblins vs Gnomes',
  BRM: 'Blackrock Mountain',
  TGT: 'The Grand Tournament',
  LOE: 'League of Explorers',
  OG: 'Whispers of the Old Gods',
  KARA: 'One Night in Karazhan',
  GANGS: 'Mean Streets of Gadgetzan',
  UNGORO: "Journey to Un'Goro",
  ICECROWN: 'Knights of the Frozen Throne',
  LOOTAPALOOZA: 'Kobolds and Catacombs',
  GILNEAS: 'The Witchwood',
  BOOMSDAY: 'The Boomsday Project',
  TROLL: "Rastakhan's Rumble",
  DALARAN: 'Rise of Shadows',
  ULDUM: 'Saviors of Uldum',
  DRAGONS: 'Descent of Dragons',
  YEAR_OF_THE_DRAGON: "Galakrond's Awakening",
  DEMON_HUNTER_INITIATE: 'Demon Hunter Initiate',
  BLACK_TEMPLE: 'Ashes of Outland',
  SCHOLOMANCE: 'Scholomance Academy',
  DARKMOON_FAIRE: 'Madness at the Darkmoon Faire',
  THE_BARRENS: 'Forged In The Barrens',
  STORMWIND: 'United in Stormwind',
  ALTERAC_VALLEY: 'Fractured in Alterac Valley',
  THE_SUNKEN_CITY: 'Voyage to the Sunken City',
  REVENDRETH: 'Murder at Castle Nathria',
  PATH_OF_ARTHAS: 'Path of Arthas',
  RETURN_OF_THE_LICH_KING: 'March of the Lich King',
  WONDERS: 'Caverns of Time',
  BATTLE_OF_THE_BANDS: 'Festival of Legends',
  TITANS: 'TITANS',
  WILD_WEST: 'Showdown in the Badlands',
  WHIZBANGS_WORKSHOP: "Whizbang's Workshop",
  ISLAND_VACATION: 'Perils in Paradise',
  SPACE: 'The Great Dark Beyond',
  EMERALD_DREAM: 'Into the Emerald Dream',
  THE_LOST_CITY: 'The Lost City',
  TIME_TRAVEL: 'Across the Timeways',
  CATACLYSM: 'CATACLYSM',
  ESCAPEFROM_VIOLET_HOLD: 'Escape From Violet Hold',
  EXPERT1: 'Classic',
  LEGACY: 'Legacy',
  TB: 'Tavern Brawl',
  BATTLEGROUNDS: 'Battlegrounds',
  BASIC: 'Basic',
  VANILLA: 'VANILLA'
};

export const hs: Game.Client<'HS'> = {
  code: 'HS',
  name: 'Hearthstone',
  scoreables(e) {
    const keys: Partial<Record<HS.GameEventName, [string, Emoji]>> = {
      // OnEntityWillTakeDamage: ['damaged', '✊'],
      // OnPlayerDraw: ['drawn', '🫳'],
      // OnOpponentPlay: ['played', '👇'],
      // OnPlayerMinionAttack: ['attacked', '👊'],
      // OnOpponentMinionAttack: ['defended', '🤚']
      OnEntityWillTakeDamage: ['damaged', '🫨'], // 💥
      OnPlayerDraw: ['drawn', '🥏'],
      OnOpponentPlay: ['played', '🫳'], // 🎯
      OnPlayerMinionAttack: ['attacked', '⚔️'],
      OnOpponentMinionAttack: ['defended', '🛡️'],
      // OnPlayerGet: '',
      // OnPlayerPlay: '',
      // OnPlayerHandDiscard: '',
      // OnPlayerMulligan: '',
      // OnPlayerDeckDiscard: '',
      // OnPlayerPlayToDeck: '',
      // OnPlayerPlayToHand: '',
      // OnPlayerPlayToGraveyard: '',
      // OnPlayerCreateInDeck: '',
      // OnPlayerCreateInPlay: '',
      // OnPlayerJoustReveal: '',
      // OnPlayerDeckToPlay: '',
      // OnPlayerHeroPower: '',
      // OnPlayerFatigue: '',
      // OnPlayerMinionMouseOver: '',
      // OnPlayerHandMouseOver: '',
      // OnOpponentDraw: '',
      // OnOpponentGet: '',
      // OnOpponentHandDiscard: '',
      // OnOpponentMulligan: '',
      // OnOpponentDeckDiscard: '',
      // OnOpponentPlayToDeck: '',
      // OnOpponentHandToDeck: '',
      // OnOpponentPlayToHand: '',
      // OnOpponentPlayToGraveyard: '',
      // OnOpponentSecretTriggered: '',
      // OnOpponentCreateInDeck: '',
      // OnOpponentCreateInPlay: '',
      // OnOpponentJoustReveal: '',
      // OnOpponentDeckToPlay: '',
      // OnOpponentHeroPower: '',
      // OnOpponentFatigue: '',
      // OnOpponentMinionMouseOver: '',
      OnGameStart: ['starts', '💫']
      // OnGameEnd: ['ended', '🎬'],
      // OnGameWon: '',
      // OnGameLost: '',
      // OnGameTied: '',
      // OnInMenu: '',
      // OnTurnStart: '',
      // OnMouseOverOff: '',
      // OnModeChanged: ''
    };
    return keys[e as HS.GameEventName];
  },
  scored(items) {
    return (items || []).map(e => {
      const [title, icon] = hs.scoreables(e.eventable) ?? [e.eventable, '♾️'];
      return { ...e, scoreable: { title, icon } };
    });
  }
};
