/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MailForwarder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MailIdentity": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "MailStore": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "MyWeb": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}

import "sst"
export {}